name: releaser

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+alpha[0-9]+"
      - "v[0-9]+\\.[0-9]+\\.[0-9]+beta[0-9]+"
      - "v[0-9]+\\.[0-9]+\\.[0-9]+rc[0-9]+"
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"
  # 手動実行したい場合は下をアンコメント
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'タグ名 (例: v1.2.3)。空なら push タグから取得'
  #       required: false

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
      ARCH: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            git
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-compiler-rt
            mingw-w64-x86_64-lld
            mingw-w64-x86_64-lua51
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-tools
          update: true

      - name: Build
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          mkdir -p build
          cd build
          rm -f CMakeCache.txt
          cmake -GNinja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_C_STANDARD=11 \
            -DCMAKE_C_STANDARD_REQUIRED=ON \
            -DCMAKE_C_EXTENSIONS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            ..
          ninja -v
          echo "Built files:"
          ls -l bin || true

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: MINGW64-bin
          path: build/bin/**
          if-no-files-found: error
          retention-days: 90
          compression-level: 6

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Resolve tag
        id: get_version
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            # push タグトリガー時は refs/tags/xxx
            RAW="${GITHUB_REF#refs/tags/}"
            TAG="$RAW"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Resolved tag: $TAG"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MINGW64-bin
          path: MINGW64-bin

      - name: Package zip
        run: |
          set -eux
          TAG='${{ steps.get_version.outputs.tag }}'
          cd MINGW64-bin
          zip -r ../aviutl_bridge_${TAG}_x86_64.zip .
          cd ..
          ls -l aviutl_bridge_${TAG}_x86_64.zip

      - name: Create Release (draft)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          release_name: ${{ steps.get_version.outputs.tag }}
          draft: true
          prerelease: false
          body: |
            ### ダウンロード
            - aviutl_bridge_${{ steps.get_version.outputs.tag }}_x86_64.zip

            ### 変更点
            - ここに変更点を書いてください

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./aviutl_bridge_${{ steps.get_version.outputs.tag }}_x86_64.zip
          asset_name: aviutl_bridge_${{ steps.get_version.outputs.tag }}_x86_64.zip
          asset_content_type: application/zip

      # softprops/action-gh-release を使う代替 (上2ステップと排他)：
      # - name: Release via softprops
      #   uses: softprops/action-gh-release@v2
      #   if: always()  # 条件を調整
      #   with:
      #     draft: true
      #     tag_name: ${{ steps.get_version.outputs.tag }}
      #     name: ${{ steps.get_version.outputs.tag }}
      #     files: |
      #       aviutl_bridge_${{ steps.get_version.outputs.tag }}_x86_64.zip
      #     body: |
      #       ### ダウンロード
      #       - aviutl_bridge_${{ steps.get_version.outputs.tag }}_x86_64.zip
      #       ### 変更点
      #       - ここに変更点
